GET http://localhost:3000/api/places HTTP/1.1
Content-Type: application/json

//{
//  "_id": "60fa7d9a966c222638cf8d97"
//}
{
  "coordinates": {
    "lat":13.484139, 
    "lng": -88.191460
  },
  "distance": 400
}

###

POST http://localhost:3000/api/places HTTP/1.1
Content-Type: application/json

{
  "place": {
    "category": ["comedor", "casera"],
    "contact": {
      "socialMedia": [
        {
          "media": "Instagram",
          "user": "comedor.rosita"
        }
      ],
      "telephone": [
        "4235555553"
      ]
    },
    "description": "bonito lugar para ir a comer con toda tu familia",
    "gallery": null,
    "ubication": "por la ciudad jardin",
    "location": {
      "type": "Point",
      "coordinates": [ 
        13.483450, 
        -88.192265
      ]
    },
    "name": "comedor rosita",
    "rating": null,
    "schedule": [
      {
        "interval": [
          "lunes",
          "viernes"
        ],
        "from": "7:30",
        "to": "17:00"
      },
      {
        "interval": "sabado",
        "from": "9:00",
        "to": "13:00"
      }
    ]
  }
}

###

PUT http://localhost:3000/api/places HTTP/1.1
Content-Type: application/json

{
  "place": {
    "category": ["", ""],
    "contact": {
      "socialMedia": [
        {
          "media": "Instagram",
          "user": "comedor.rosita"
        }
      ],
      "telephone": [
        "4235555553"
      ]
    },
    "description": "bonito lugar para ir a comer con toda tu familia",
    "gallery": null,
    "ubication": "por la ciudad jardin",
    "location": {
      "type": "Point",
      "coordinates": [ 
        13.483450, 
        -88.192265
      ]
    },
    "name": "comedor rosita",
    "rating": null,
    "schedule": [
      {
        "interval": [
          "lunes",
          "viernes"
        ],
        "from": "7:30",
        "to": "17:00"
      },
      {
        "interval": "sabado",
        "from": "9:00",
        "to": "13:00"
      }
    ]
  },
  "_id"
}

###

PATCH http://localhost:3000/api/places HTTP/1.1
Content-Type: application/json

{
  "patch": {
    "name": "pupuseria lorena peña nieto"
  },
  "_id": "60fa6aed48353712a3d772a1"
}
