//app.use(express.urlencoded({ extended: true }));
//app.use(express.static('./www'));
//app.use('/places/gallery', express.static('./assets/uploads/places'));
//app.use('/users/photo', express.static('./assets/uploads/users'));
//app.use('/api/places', placesRoutes);
//app.use('/api/users', usersRoutes);
////console.log(require('crypto').randomBytes(64).toString('hex'));
import express from "express";
import morgan from "morgan";
import pkg from "../package.json";
import placesRoutes from "./routes/places";
import authenticationRoutes from "./routes/authentication";
import usersRoutes from './routes/users';
import { createRoles } from './libs/initSetup';
//import { randomBytes } from 'crypto';
import dotenv from "dotenv";
const app = express();
createRoles();
dotenv.config();
//console.log(randomBytes(64).toString("hex"));
app.set("pkg", pkg);
app.use(morgan("dev"));
app.use(express.json());
app.get("/", (req, res) => {
    const { name, author, description, version } = app.get("pkg");
    res.json({ author, name, description, version });
});
app.use("/api/places", placesRoutes);
app.use("/api/authentication", authenticationRoutes);
app.use("/api/users", usersRoutes);
export default app;